version: "3.8"

services:
  database:
    image: mongo:5.0.6
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./infrastructure/build/docker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - TZ=Europe/Berlin
      - SPRING_PROFILES_ACTIVE=testdata
      - MONGODB_HOST=database
      - MONGODB_DB=shopping-cart
    depends_on:
      - database

networks:
  default:
    name: local_development_network
